avg_reprojection: false
batch_size: 1
data_path: /mnt/wext/cv_data/kitti/kitti_raw_data
dataset: kitti
disable_automasking: false
disable_median_scaling: false
disparity_smoothness: 0.001
do_overfit: true
eval_eigen_to_benchmark: false
eval_mono: false
eval_out_dir: null
eval_split: eigen
eval_stereo: false
ext_disp_to_eval: null
frame_ids:
- 0
- -1
- 1
height: 192
learning_rate: 0.0001
load_weights_folder: null
log_dir: /home/master/tmp
log_frequency: 1
max_depth: 100.0
min_depth: 0.1
model_name: mono_model
models_to_load:
- encoder
- depth
- pose_encoder
- pose
no_cuda: false
no_eval: false
no_ssim: false
num_epochs: 50
num_layers: 18
num_workers: 0
png: true
pose_model_input: pairs
pose_model_type: separate_resnet
post_process: false
pred_depth_scale_factor: 1
predictive_mask: false
save_frequency: 50
save_pred_disps: false
scales:
- 0
- 1
- 2
- 3
scheduler_step_size: 50
split: eigen_full
use_stereo: false
v1_multiscale: false
weights_init: pretrained
width: 640
